### PR TITLE
Extra changes for Sky FABRICation 3

### PR DESCRIPTION
**Pull request by KonSola5**
A new PR, since MSandro made an whoopsie. But this will also enable easier sync with MSandro's changes, so win/win.

### CODE REVIEW

**Comment by KonSola5** [comment]
Due to a Botania chapter redesign, the descriptions are lost.
That's a great redesign by the way! 👍
But that also means rewriting quest descriptions again. Yay.

**Comment by MSandro** [comment]
I will add the Descriptions for the Botania and Bewitchment chapters in my next commit.
Thank you for your work on the IndRev chapter.

**Comment by KonSola5** [comment]
Also up coming: Retexture of TiC Tools to better match ingots they come from.

pickaxes

**Comment by KonSola5** [comment]
The new TiC Materials:
tic

Knightmetal actually has Piercing II (is it too powerful or not?)

Knightmetal and Neutronium can also be used to embellish armor!
Embellishing Plate Armor with Neutronium yields a wannabe Infinity Armor (decorative only, no special abilities).

Neutronium Embelished Armor

The only things that are missing: Repair materials for Knightmetal and Fiery tools.

**Comment by MSandro** [comment]
> The new TiC Materials: 
> Knightmetal actually has Piercing II (is it too powerful or not?)

Great idea, i think its fine 👍

**Comment by KonSola5** [comment]
Also changed the Relic Quests, so they don't have NBT data of the owner. (You probably added the relic quests from items in inventory, that's why they had your UUID.)

**Comment by MSandro** [comment]
Thank you so much for your help.
I will try to release v0.6.0 in the next few days.

**Comment by KonSola5** [comment]
One more thing to state:
In Create Chapter in the Windmill quest, I stated about 256 sail-like blocks to max out.
But it's actually 128 of those.

You can't add repair materials to tools made only out of molten metal. (Could be possible in a very hacky way to add a modifier that allows a tool to be repaired using fiery/knightmetal).
Repair kits still work though.

**Comment by MSandro** [comment]
image
thans, I have edited the description.

In case of TConstruct improvements, I think this can be done in future updates.

**Comment by KonSola5** [comment]
A bug that I found:
When creating a new world, after the pack-mode selection screen, no Origin selection screen nor inventory unlock is shown to a player.

Edit: Submiting the very first quests brought up the aforementioned things.
Maybe tell the player that they need to open their quest book first?

**Comment by MSandro** [comment]
Thanks I will try to reproduce it.

**Pull request merged**
