### PR TITLE
Early Game redesign

### PR DESCRIPTION
**Pull request by KonSola5**
Previously, the alternative branches were just additional quests, from where game proceeded like the normal Simple Tree Island.
Not anymore.
Alternative early-game routes were changed a bit so that Saplings are obtainable only after getting a Flint Mesh.

questline

## Simple Tree Island
Its progression wasn't changed, since it's a standard Skyblock experience.
The quests were rearranged a bit though.
This earlygame can obtain String right away because it starts with a tree!

## Bamboo Island
The weird mechanic of "damaging yourself to obtain tree leaves" was replaced with a little bit different progression.
*But, how do you sieve when you don't have vanilla wood?*
Rubber ExNihilo utilities were replaced with a bit more matching Stripped Bamboo/Bone utilities.
bamboo
Added an alternative recipe for Wooden Bucket because this earlygame can't obtain logs right away:
kibe_wooden_bucket_alt
This earlygame obtains first String by killing Spiders.

## Fishing Island
Removed Oak Saplings from the fishing pool, and added Oak Logs in their place.

This earlygame obtains String from fishing or by killing Spiders (the quest will still require to kill 5 spiders).

Defeating 5 spiders in Bamboo or Fishing Islands will give the player a nice reward :)

bane_of_spiders

### CODE REVIEW

**Comment by KonSola5** [comment]
Also: Changed Grout recipe so that it requires a Create Mixer to craft, and Alloy Forge is required to smelt it.

The second crook quest (after the Flint Mesh) won't appear if a player chose Simple Tree Island.

**Comment by MSandro** [comment]
good job 👍

**Comment by KonSola5** [comment]
The Bone Crucible may be a bit too expensive though, when I playtested the Bamboo Island I got a Flint Mesh before getting all of those necessary Bones.

**Comment by KonSola5** [comment]
- Changed the Nether Star recipe, now requires an Implosion Compressor (if it can survive 64 nukes, why not a Wither?)
Feedback is welcome.

star

- Added a Bone Knife (and this is my first custom item utilizing Java reflection, wouldn't be possible without help from latviandev's Discord)
- Made a Bone Crucible and Bone Strainer cheaper by making it an in-world craft utilizing the Bone Knife.

**Pull request merged**
