### PR TITLE
Create Sifter mod, adjustments, and more coming.

### PR DESCRIPTION
**Pull request by KonSola5**
This mod adds a new way to automate sieving - a Create Sifter!
It can accept meshes (needed to make custom meshes interchangeable 1:1 because it isn't compatible with FabricaeExNihilo).

Positive aspects of adding such mod:
- Easier sieving automation,
- Automation not breaking after items run out,
- No spilling item entities, which means less TPS lag.

One nuisance:
- You must use blacklistable item output solution to extract items from the sifter, else the block being sieved will be extracted too.

Known bugs:
- 5 custom meshes added don't render correctly in Create Sifter (added a tooltip to them to mark that it's a known bug)
- Does not show need for Waterlogged (also added a tooltip for items that require waterlogged sieves to obtain).

### CODE REVIEW

**Comment by KonSola5** [comment]
- Meshes: These are exchangeable 1:1 using crafting.
obraz

- The Create Sifter itself (variant with mesh to the right).
sifter

 - The REI overflow, because some recipes have a lot of outputs.
The outputs have the same excepted value as sieving in sieves, though automating using Create Sifter requires more SU, because there's no "5x5 sieves" mechanic.
obraz

**Comment by KonSola5** [comment]
- Added "Twilit" trait to all 3 custom Twilight Forest materials
(suprised that the compat traits are still here)
- Nerfed Knightmetal from Piercing II to Piercing I (it was too powerful, +2 damage from Twilit is enough)

**Comment by KonSola5** [comment]
No more cheeses regarding Alloy Forge (the most notable ones were Platinum, Aluminum and Steel)

**Comment by KonSola5** [comment]
- Added a new "Quest Additions" mod, it adds new quest criteria for usage in quests.

With this mod, some changes were made to the questbook:

- The Alloy Forge quest now requires to build the Alloy Forge structure and right-click it.
- Some quests in Mechanical Age had quests, which were completed by crafting one of the metioned items.
With the Quest Additions mod, they don't need to be in the filter!
- Added quests to "The Beginning" and "Mechanical Age" chapters guiding players to get some Shroomlight for first Electron Tubes.
- Renamed "Small Pile of Glowstone Dust" to "Shroomlight Dust".

Some changes to Spectrum:
- Both Mermaids Brush and Quitoxic Reeds will only reveal after getting some Onyx Shards.
- Repositioned their respective advancements and quests to focus on the requirement of Onyx Shard.
- Unhidden the "collect mermaids gem" and "collect quitoxic reeds" advancements since the player won't stumble upon them randomly in this pack

**Comment by MSandro** [comment]
Great job, thank you very much.

**Comment by KonSola5** [comment]
- Added the Compressed Quartz Block w/ recipes and an Implosion Compressor recipe for the Nether Quartz Singularity (the singularity is not added yet to Infinity Catalyst's recipe)
- Made a hack that allows for Looting to function on TiC swords - by enchanting them with appropriate Looting Level. (The Looting enchantment is hidden)
- _Staff of Travelling modifier might be also possible with this hack._

This sadly also introduces a bug:
- You can grind the Looting indefinitely for XP. It can't be fixed.

**Pull request merged**
