### PR TITLE
Proposed changes for Sky FABRICation 3

### PR DESCRIPTION
**Pull request by KonSola5**
# Proposed changes for Sky FABRICation 3

<ul>
    <li>Many Questbook edits, including a redesigned Create chapter, corrections and updates for some of the quests, 2 new Endgame Quest Chapters: Spatial Harvesters and Endgame.</li>
    <li>Added some of the MI Metals as materials for Hephaestus/Tinker's Construct Tools, making them also meltable.</li>
    <li>Rebalanced Industrial Revolution's ore processing:
        <ul>
            <li>Industrial Smelter is renamed to Industrial Smeltery, it now melts metals into their Hephaestus molten form, at the rate of regular Smeltery by default.</li>
            <li>Condenser is renamed to Ingot Former, now it forms ingots from molten metals.</li>
            <li>Purified Ore Chunks now are made from raw ore instead of ore blocks. The purification -> melting -> ingot forming process allows for getting 2 ingots from 1 raw ore, giving some competition to Modern Industrialization's ore processing.</li>
            <li>For clarification: MI gives 1.5 ingots per raw ore, Hephaestus gives 1.33 ingots per raw ore, new IndRev ore processing can give 2 ingots per raw ore.</li>
            <li>For ore purification you now need to use MI's Sulfuric Acid instead of IndRev one, the IndRev has been disabled.</li>
            <li>4 new purified ore chunks have been added: Uranium, Nickel, Zinc and Cobalt.</li>
        </ul>
    </li>
    <li>3 Copper + 1 Tin -> 4 Bronze if you use an End Stone Brick Forge.</li>
    <li>Blacklisted Cardboard Boxes, AE2 Cables and MI machines from Carrier mod carrying.</li>
    <li>Retextured IndRev's Purified Ore Chunks to better match their ore counterparts.</li>
    <li>Retextured and renamed AE2Additions items and blocks to be consistent with each other and with AE2.</li>
    <li>Properly localized Spectrum, FabricaeExNihilo and TechReborn fluids.</li>
    <li>Given quite a lot of tags to items to add functions:
        <ul>
            <li>Added tool tags to Hephaestus tools for them to be able to be equipped in Inventorio Slots.</li>
            <li>Given mambience sword/tool/bow tags to give non-vanilla swords/tools/bows fancy sound effects.</li>
            <li>Added material tags to some of the MI metals to make them Hephaestus materials.</li>
        </ul>
    </li>
    <li>Removed redundant items, fluids and TR Fluid Cells from REI.</li>
    <li>Record Fragment recipe now accepts any music disc, instead of only disc 13.</li>
    <li>An ability to recycle Croparia Seeds in the MI Centrifuge, since Croparia one works on its own proprietary energy system and it's super slow. Also gives transparency, what are the odds of getting a fruit from recycling a seed!</li>
    <li>DML Data Model changes for balance with Simulacrum:
        <ul>
            <li>Basic: 8 -> 16</li>
            <li>Advanced: 16 -> 128</li>
            <li>Superior: 32 -> 256</li>
            <li>Self-Aware: 64 -> 512</li>
        </ul>
    </li>
	<li>Changed C:C&A Diamond Grit in Diamond Mesh's recipe to MI Diamond Dust.</li>
	<li>Changed Netherite Mesh's recipe: now it requires you to cast 3 Netherite Ingots on the Diamond Mesh. This improves the timing of the mesh, because previously it was too late to be useful.</li>
	<li>Processing ores in Alloy Forge now yields correct ingots! Yay!</li>
	<li>Spectrum's Stratine Ore and Hephaestus' Cobalt Ore are now obtainable using a Gold Drill.</li>
</ul>

- Added the ability to craft large table Endgame crafting recipes using large Mechanical Crafting recipes (Crafting ingredients only).
- REI does not feel good about rendering 9x9 recipes correctly... Infinity Ingot
- New `/emergency` command, gives an emergency item, has a 5 minute cooldown.
- Ancient Ruins now spawn in Sky Islands! 🎉🎉🎉 They are less common than in the default config, but waaaay more common than MSandro's config. (aka, you can find another Ancient Ruin in 1000 blocks from the previous one, saving the precious time and disk space).

## For developers/debugging:
- A hidden quest chapter containing every Spectrum progression trigger located in the "spectrum:progression" invisible advancement tree.

## Not fixed:
- Lack of Void Blossom boss,
- Absolutely broken Croparia Items,
- Poor MI Diesel Drill breaking speed.
- Didn't find a way to make Hephaestus tools compatible with FTB Ultimine...

### CODE REVIEW

**Comment by KonSola5** [comment]
Also missing: Mechanical Crafting recipes for Ultimate foods (for some reason they don't load)

**Comment by MSandro** [comment]
wow Thank you very much for your work.

**Comment by MSandro** [comment]
@KonSola5 whats your Curseforge name? I would like to add you as an developer on the Modpack Page.

**Comment by KonSola5** [comment]
konsola5

**Comment by MSandro** [comment]
Thanks for your contribution, it's a big help. I currently have hardly any time to take care of the project, which I think is a pity myself. I will take a closer look at your changes in the next few days and then probably merge and release them as an update in the next 2 weeks.

**Comment by KonSola5** [comment]
One thing to note about the quests:
There is a missing item in the center checkmark of "Building" tab section (it's set to staffofbuilding:infinite_builder_staff, but there's no "Staff of Building" mod in this modpack). It should be changed or removed altogether.

**Comment by MSandro** [comment]
> One thing to note about the quests: There is a missing item in the center checkmark of "Building" tab section (it's set to staffofbuilding:infinite_builder_staff, but there's no "Staff of Building" mod in this modpack). It should be changed or removed altogether.

weird, thanks I will change it.

**Comment by KonSola5** [comment]
Noticed that a new branch has been created, switched PR to that new branch.

**Comment by MSandro** [comment]
> Noticed that a new branch has been created, switched PR to that new branch.

Yes, I am working on v0.6.0 and I am merging your changes their.

**Comment by KonSola5** [comment]
A prototype of a new addition: Custom TiC tools made out of Twilight Forest materials!
steeleaf

Here's Steeleaf, makes decently fast and sharp tools, has low durability, but can resist 75% durability damage when the player is in sunlight. (Balanced around actual Steeleaf Tools).

fiery

Fiery - makes good tools and weapons, has medium durability, and sets things on fire.
Again, balanced around actual Fiery tools.

**Comment by KonSola5** [comment]
Also coming: A Step-Up modifier fix, using emi's step_up attribute, that's used by ex. Spectrum.
stepup

**Comment by MSandro** [comment]
Thanks for your awesome help @KonSola5
Sorry, I didn't want to finally merge the pull request, I made a mistake operating the Git command. I hope that doesn't cause you any problems.
I have a request, Could you have a look why the gold drill has no outputs when you have activated the expert mode? Maybe you have an idea what it is, I didn't remove it explicitly.
```
/kubejs custom_command expert
```

**Comment by KonSola5** [comment]
I didn't activate the new Expert Mode yet, the comments about the recipes were made from reading the changed .json's themselves.
But I will investigate this when I will be having free time.

**Pull request merged**
